apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubestash-operator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    apiVersion: config.kubestash.com/v1alpha1
    kind: KubeStashConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
      certDir: /var/serving-cert
    leaderElection:
      leaderElect: false
      resourceName: cba9d7ad.kubestash.com
    {{- if include "appscode.license" . }}
    license:
      path: /var/run/secrets/appscode/license/key.txt
      apiService: {{ .Values.licenseApiService }}
    {{- end }}
    webhookInfo:
      validating:
        enable: {{ .Values.apiserver.enableValidatingWebhook }}
        name: {{ include "kubestash-operator.fullname" . }}
      mutating:
        enable: {{ .Values.apiserver.enableMutatingWebhook }}
        name: {{ include "kubestash-operator.fullname" . }}
    docker:
      registry: {{ .Values.operator.registry }}
      image: {{ .Values.operator.repository }}
      tag: {{ .Values.operator.tag }}
