project:
  name: KubeStash by AppsCode
  shortName: KubeStash
  url: https://github.com/stashed/kubestash
  description: KubeStash a successor of Stash by AppsCode is a Kubernetes native disaster recovery tool.
  app: KubeStash operator
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubestash-operator
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: kubestash-operator
  namespace: kubestash
