{{- if .Values.apiserver.enableMutatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubestash-operator.fullname" . }}
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-storage-kubestash-com-v1alpha1-backupstorage
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: mbackupstorage.kb.io
    rules:
      - apiGroups:
          - storage.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backupstorages
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-storage-kubestash-com-v1alpha1-retentionpolicy
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: mretentionpolicy.kb.io
    rules:
      - apiGroups:
          - storage.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - retentionpolicies
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-core-kubestash-com-v1alpha1-backupblueprint
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: mbackupblueprint.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backupblueprints
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-core-kubestash-com-v1alpha1-hooktemplate
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: mhooktemplate.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - hooktemplates
    sideEffects: None
{{ end }}
