{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubestash-operator.fullname" . }}
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-storage-kubestash-com-v1alpha1-backupstorage
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vbackupstorage.kb.io
    rules:
      - apiGroups:
          - storage.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backupstorages
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-storage-kubestash-com-v1alpha1-repository
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vrepository.kb.io
    rules:
      - apiGroups:
          - storage.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - repositories
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-storage-kubestash-com-v1alpha1-retentionpolicy
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vretentionpolicy.kb.io
    rules:
      - apiGroups:
          - storage.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - retentionpolicies
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-core-kubestash-com-v1alpha1-backupbatch
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vbackupbatch.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backupbatches
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-core-kubestash-com-v1alpha1-backupblueprint
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vbackupblueprint.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backupblueprints
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-core-kubestash-com-v1alpha1-backupconfiguration
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vbackupconfiguration.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backupconfigurations
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-core-kubestash-com-v1alpha1-backupsession
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vbackupsession.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backupsessions
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-core-kubestash-com-v1alpha1-hooktemplate
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vhooktemplate.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - hooktemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kubestash-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-core-kubestash-com-v1alpha1-restoresession
      caBundle: {{ b64enc .Values.apiserver.ca }}
    failurePolicy: Fail
    name: vrestoresession.kb.io
    rules:
      - apiGroups:
          - core.kubestash.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - restoresessions
    sideEffects: None
{{ end }}
