//go:build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"kmodules.xyz/client-go/api/v1"
	apiv1 "kmodules.xyz/offshoot-api/api/v1"
	"kubestash.dev/apimachinery/apis"
	corev1alpha1 "kubestash.dev/apimachinery/apis/core/v1alpha1"
	storagev1alpha1 "kubestash.dev/apimachinery/apis/storage/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedVirtualMachines) DeepCopyInto(out *AllowedVirtualMachines) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = new(apis.AllowedNamespaces)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedVirtualMachines.
func (in *AllowedVirtualMachines) DeepCopy() *AllowedVirtualMachines {
	if in == nil {
		return nil
	}
	out := new(AllowedVirtualMachines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStorage) DeepCopyInto(out *BackupStorage) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStorage.
func (in *BackupStorage) DeepCopy() *BackupStorage {
	if in == nil {
		return nil
	}
	out := new(BackupStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBTBackupOptions) DeepCopyInto(out *CBTBackupOptions) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TTLDuration != nil {
		in, out := &in.TTLDuration, &out.TTLDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RuntimeSettings != nil {
		in, out := &in.RuntimeSettings, &out.RuntimeSettings
		*out = new(apiv1.RuntimeSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBTBackupOptions.
func (in *CBTBackupOptions) DeepCopy() *CBTBackupOptions {
	if in == nil {
		return nil
	}
	out := new(CBTBackupOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullBackupOptions) DeepCopyInto(out *FullBackupOptions) {
	*out = *in
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(corev1alpha1.SchedulerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JobTemplate != nil {
		in, out := &in.JobTemplate, &out.JobTemplate
		*out = new(apiv1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryConfig != nil {
		in, out := &in.RetryConfig, &out.RetryConfig
		*out = new(corev1alpha1.RetryConfig)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullBackupOptions.
func (in *FullBackupOptions) DeepCopy() *FullBackupOptions {
	if in == nil {
		return nil
	}
	out := new(FullBackupOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeVirtArchiver) DeepCopyInto(out *KubeVirtArchiver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeVirtArchiver.
func (in *KubeVirtArchiver) DeepCopy() *KubeVirtArchiver {
	if in == nil {
		return nil
	}
	out := new(KubeVirtArchiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeVirtArchiver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeVirtArchiverList) DeepCopyInto(out *KubeVirtArchiverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeVirtArchiver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeVirtArchiverList.
func (in *KubeVirtArchiverList) DeepCopy() *KubeVirtArchiverList {
	if in == nil {
		return nil
	}
	out := new(KubeVirtArchiverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeVirtArchiverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeVirtArchiverSpec) DeepCopyInto(out *KubeVirtArchiverSpec) {
	*out = *in
	if in.VirtualMachines != nil {
		in, out := &in.VirtualMachines, &out.VirtualMachines
		*out = new(AllowedVirtualMachines)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupStorage != nil {
		in, out := &in.BackupStorage, &out.BackupStorage
		*out = new(BackupStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionSecret != nil {
		in, out := &in.EncryptionSecret, &out.EncryptionSecret
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.FullBackup != nil {
		in, out := &in.FullBackup, &out.FullBackup
		*out = new(FullBackupOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.ManifestBackup != nil {
		in, out := &in.ManifestBackup, &out.ManifestBackup
		*out = new(ManifestBackupOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.CBTBackup != nil {
		in, out := &in.CBTBackup, &out.CBTBackup
		*out = new(CBTBackupOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(storagev1alpha1.BackupConfigDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeVirtArchiverSpec.
func (in *KubeVirtArchiverSpec) DeepCopy() *KubeVirtArchiverSpec {
	if in == nil {
		return nil
	}
	out := new(KubeVirtArchiverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeVirtArchiverStatus) DeepCopyInto(out *KubeVirtArchiverStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VirtualMachines != nil {
		in, out := &in.VirtualMachines, &out.VirtualMachines
		*out = make([]VirtualMachineArchiverStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeVirtArchiverStatus.
func (in *KubeVirtArchiverStatus) DeepCopy() *KubeVirtArchiverStatus {
	if in == nil {
		return nil
	}
	out := new(KubeVirtArchiverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestBackupOptions) DeepCopyInto(out *ManifestBackupOptions) {
	*out = *in
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(corev1alpha1.SchedulerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JobTemplate != nil {
		in, out := &in.JobTemplate, &out.JobTemplate
		*out = new(apiv1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryConfig != nil {
		in, out := &in.RetryConfig, &out.RetryConfig
		*out = new(corev1alpha1.RetryConfig)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestBackupOptions.
func (in *ManifestBackupOptions) DeepCopy() *ManifestBackupOptions {
	if in == nil {
		return nil
	}
	out := new(ManifestBackupOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineArchiverStatus) DeepCopyInto(out *VirtualMachineArchiverStatus) {
	*out = *in
	if in.LastObservedTime != nil {
		in, out := &in.LastObservedTime, &out.LastObservedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineArchiverStatus.
func (in *VirtualMachineArchiverStatus) DeepCopy() *VirtualMachineArchiverStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineArchiverStatus)
	in.DeepCopyInto(out)
	return out
}
