
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-storage-kubestash-com-v1alpha1-backupstorage
  failurePolicy: Fail
  name: mbackupstorage.kb.io
  rules:
  - apiGroups:
    - storage.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupstorages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-storage-kubestash-com-v1alpha1-retentionpolicy
  failurePolicy: Fail
  name: mretentionpolicy.kb.io
  rules:
  - apiGroups:
    - storage.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - retentionpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kubestash-com-v1alpha1-backupblueprint
  failurePolicy: Fail
  name: mbackupblueprint.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupblueprints
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kubestash-com-v1alpha1-hooktemplate
  failurePolicy: Fail
  name: mhooktemplate.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hooktemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kubestash-com-v1alpha1-backupconfiguration
  failurePolicy: Fail
  name: vbackupconfiguration.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupconfigurations
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-storage-kubestash-com-v1alpha1-backupstorage
  failurePolicy: Fail
  name: vbackupstorage.kb.io
  rules:
  - apiGroups:
    - storage.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupstorages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-storage-kubestash-com-v1alpha1-repository
  failurePolicy: Fail
  name: vrepository.kb.io
  rules:
  - apiGroups:
    - storage.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-storage-kubestash-com-v1alpha1-retentionpolicy
  failurePolicy: Fail
  name: vretentionpolicy.kb.io
  rules:
  - apiGroups:
    - storage.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - retentionpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kubestash-com-v1alpha1-backupbatch
  failurePolicy: Fail
  name: vbackupbatch.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupbatches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kubestash-com-v1alpha1-backupblueprint
  failurePolicy: Fail
  name: vbackupblueprint.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupblueprints
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kubestash-com-v1alpha1-backupsession
  failurePolicy: Fail
  name: vbackupsession.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupsessions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kubestash-com-v1alpha1-hooktemplate
  failurePolicy: Fail
  name: vhooktemplate.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hooktemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kubestash-com-v1alpha1-restoresession
  failurePolicy: Fail
  name: vrestoresession.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - restoresessions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kubestash-com-v1alpha1-backupconfiguration
  failurePolicy: Fail
  name: vbackupconfiguration.kb.io
  rules:
  - apiGroups:
    - core.kubestash.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupconfigurations
  sideEffects: None
