apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubestash-operator.fullname" . }}
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["*"]
  - apiGroups:
      - core.kubestash.com
      - kubedb.com
      - snapshot.storage.k8s.io
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - storage.kubestash.com
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - appcatalog.appscode.com
    resources:
      - "*"
    verbs: ["get"]
  - apiGroups:
      - config.kubestash.com
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - addons.kubestash.com
    resources:
      - "*"
    verbs: [ "*" ]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: ["create"]
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs: ["get"]
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs: ["get"]
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
    verbs: ["get"]
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: ["get", "list", "create", "patch", "watch"]
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - roles
      - rolebindings
      - clusterrolebindings
    verbs: ["get","list", "watch", "create", "delete", "patch", "update"]