apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubestash-operator.fullname" . }}-crd-installer
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups:
      - addons.kubestash.com
      - core.kubestash.com
      - storage.kubestash.com
    resources:
      - "*"
    verbs: ["*"]
