apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubestash-operator.serviceAccountName" . }}-crd-installer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
