apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubestash
  name: backupverificationsession.core.kubestash.com
spec:
  group: core.kubestash.com
  names:
    categories:
    - kubestash
    - appscode
    - all
    kind: BackupVerificationSession
    listKind: BackupVerificationSessionList
    plural: backupverificationsession
    singular: backupverificationsession
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.backupVerifier.name
      name: Verifier
      type: string
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.duration
      name: Duration
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BackupVerificationSession represent one backup verification run
          for the target(s) pointed by the respective BackupConfiguration or BackupBatch
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BackupVerificationSessionSpec specifies the information related
              to the respective backup verifier, session, repository and snapshot.
            properties:
              backupVerifier:
                description: BackupVerifier points to the respective BackupVerification
                  which is used for verification.
                properties:
                  name:
                    default: ""
                    description: 'Name of the referent. This field is effectively
                      required, but due to backwards compatibility is allowed to be
                      empty. Instances of this type with an empty value here are almost
                      certainly wrong. TODO: Add other useful fields. apiVersion,
                      kind, uid? More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Drop `kubebuilder:default` when controller-gen doesn''t
                      need it https://github.com/kubernetes-sigs/kubebuilder/issues/3896.'
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              repository:
                type: string
              retryLeft:
                description: RetryLeft specifies number of retry attempts left for
                  the backup verification session. If this set to non-zero, KubeStash
                  will create a new BackupVerificationSession if the current one fails.
                format: int32
                type: integer
              session:
                description: Session specifies the name of the session that triggered
                  this backup verification
                type: string
              snapshot:
                description: Snapshot specifies the name of the snapshot that has
                  been verified in this backup verification
                type: string
            type: object
          status:
            description: BackupVerificationSessionStatus defines the observed state
              of BackupVerificationSession
            properties:
              conditions:
                description: Conditions represents list of conditions regarding this
                  BackupSession
                items:
                  description: Condition defines an observation of a object operational
                    state.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human-readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether this field
                        is considered a guaranteed API. This field may not be empty.
                      type: string
                    severity:
                      description: Severity provides an explicit classification of
                        Reason code, so the users or machines can immediately understand
                        the current situation and act accordingly. The Severity field
                        MUST be set only when Status=False.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary util can be useful (see
                        .node.status.util), the ability to deconflict is important.
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              duration:
                description: Duration specifies the time required to complete the
                  backup verification process
                type: string
              phase:
                description: Phase represents the current state of the backup verification
                  process.
                enum:
                - Pending
                - Running
                - Succeeded
                - Failed
                type: string
              retried:
                description: Retried specifies whether this session was retried or
                  not. This field will exist only if the `retryConfig` has been set
                  in the respective backup verification strategy.
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
