apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: cert-manager
  name: backupstorages.stash.appscode.com
spec:
  group: stash.appscode.com
  names:
    kind: BackupStorage
    listKind: BackupStorageList
    plural: backupstorages
    singular: backupstorage
  scope: Namespaced
  versions:
  - name: v1beta2
    schema:
      openAPIV3Schema:
        description: BackupStorage is the Schema for the backupstorages API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                pattern: ^[a-z]([-a-z0-9]*[a-z0-9])?$
                type: string
            type: object
          spec:
            properties:
              foo:
                description: Foo is an example field of BackupStorage. Edit backupstorage_types.go
                  to remove/update
                type: string
            type: object
          status:
            description: BackupStorageStatus defines the observed state of BackupStorage
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
