//go:build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	storagev1alpha1 "kubestash.dev/apimachinery/apis/storage/v1alpha1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	v1 "kmodules.xyz/client-go/api/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendOverview) DeepCopyInto(out *BackendOverview) {
	*out = *in
	out.Storage = in.Storage
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(RetentionSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.LagBehindNewest != nil {
		in, out := &in.LagBehindNewest, &out.LagBehindNewest
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendOverview.
func (in *BackendOverview) DeepCopy() *BackendOverview {
	if in == nil {
		return nil
	}
	out := new(BackendOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupCoverage) DeepCopyInto(out *BackupCoverage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupCoverage.
func (in *BackupCoverage) DeepCopy() *BackupCoverage {
	if in == nil {
		return nil
	}
	out := new(BackupCoverage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupCoverage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupCoverageSpec) DeepCopyInto(out *BackupCoverageSpec) {
	*out = *in
	out.Cluster = in.Cluster
	if in.ManifestBackups != nil {
		in, out := &in.ManifestBackups, &out.ManifestBackups
		*out = make([]ManifestBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupCoverageSpec.
func (in *BackupCoverageSpec) DeepCopy() *BackupCoverageSpec {
	if in == nil {
		return nil
	}
	out := new(BackupCoverageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupOverview) DeepCopyInto(out *BackupOverview) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupOverview.
func (in *BackupOverview) DeepCopy() *BackupOverview {
	if in == nil {
		return nil
	}
	out := new(BackupOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupOverview) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupOverviewList) DeepCopyInto(out *BackupOverviewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupOverview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupOverviewList.
func (in *BackupOverviewList) DeepCopy() *BackupOverviewList {
	if in == nil {
		return nil
	}
	out := new(BackupOverviewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupOverviewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupOverviewSpec) DeepCopyInto(out *BackupOverviewSpec) {
	*out = *in
	out.Invoker = in.Invoker
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(v1.TypedObjectReference)
		**out = **in
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]BackupMethod, len(*in))
		copy(*out, *in)
	}
	if in.Sessions != nil {
		in, out := &in.Sessions, &out.Sessions
		*out = make([]SessionOverview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]BackendOverview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PITR != nil {
		in, out := &in.PITR, &out.PITR
		*out = new(PITROverview)
		(*in).DeepCopyInto(*out)
	}
	in.RPO.DeepCopyInto(&out.RPO)
	in.RTO.DeepCopyInto(&out.RTO)
	if in.LastSuccessfulBackupTime != nil {
		in, out := &in.LastSuccessfulBackupTime, &out.LastSuccessfulBackupTime
		*out = (*in).DeepCopy()
	}
	if in.FirstRecoveryPoint != nil {
		in, out := &in.FirstRecoveryPoint, &out.FirstRecoveryPoint
		*out = (*in).DeepCopy()
	}
	in.Timeline.DeepCopyInto(&out.Timeline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupOverviewSpec.
func (in *BackupOverviewSpec) DeepCopy() *BackupOverviewSpec {
	if in == nil {
		return nil
	}
	out := new(BackupOverviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSessionRef) DeepCopyInto(out *BackupSessionRef) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSessionRef.
func (in *BackupSessionRef) DeepCopy() *BackupSessionRef {
	if in == nil {
		return nil
	}
	out := new(BackupSessionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloneOptions) DeepCopyInto(out *CloneOptions) {
	*out = *in
	if in.DeleteAfter != nil {
		in, out := &in.DeleteAfter, &out.DeleteAfter
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloneOptions.
func (in *CloneOptions) DeepCopy() *CloneOptions {
	if in == nil {
		return nil
	}
	out := new(CloneOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIdentity) DeepCopyInto(out *ClusterIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIdentity.
func (in *ClusterIdentity) DeepCopy() *ClusterIdentity {
	if in == nil {
		return nil
	}
	out := new(ClusterIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseBackup) DeepCopyInto(out *DatabaseBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseBackup.
func (in *DatabaseBackup) DeepCopy() *DatabaseBackup {
	if in == nil {
		return nil
	}
	out := new(DatabaseBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseBackupList) DeepCopyInto(out *DatabaseBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseBackupList.
func (in *DatabaseBackupList) DeepCopy() *DatabaseBackupList {
	if in == nil {
		return nil
	}
	out := new(DatabaseBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseBackupSpec) DeepCopyInto(out *DatabaseBackupSpec) {
	*out = *in
	out.Database = in.Database
	if in.BackupConfigurations != nil {
		in, out := &in.BackupConfigurations, &out.BackupConfigurations
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.LastSuccessfulBackupTime != nil {
		in, out := &in.LastSuccessfulBackupTime, &out.LastSuccessfulBackupTime
		*out = (*in).DeepCopy()
	}
	if in.RPO != nil {
		in, out := &in.RPO, &out.RPO
		*out = new(RPOStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseBackupSpec.
func (in *DatabaseBackupSpec) DeepCopy() *DatabaseBackupSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogFailure) DeepCopyInto(out *LogFailure) {
	*out = *in
	in.Range.DeepCopyInto(&out.Range)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogFailure.
func (in *LogFailure) DeepCopy() *LogFailure {
	if in == nil {
		return nil
	}
	out := new(LogFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestBackup) DeepCopyInto(out *ManifestBackup) {
	*out = *in
	out.BackupConfiguration = in.BackupConfiguration
	if in.LastSuccessfulBackupTime != nil {
		in, out := &in.LastSuccessfulBackupTime, &out.LastSuccessfulBackupTime
		*out = (*in).DeepCopy()
	}
	in.RPO.DeepCopyInto(&out.RPO)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestBackup.
func (in *ManifestBackup) DeepCopy() *ManifestBackup {
	if in == nil {
		return nil
	}
	out := new(ManifestBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestOptions) DeepCopyInto(out *ManifestOptions) {
	*out = *in
	if in.IncludeNamespaces != nil {
		in, out := &in.IncludeNamespaces, &out.IncludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeResources != nil {
		in, out := &in.IncludeResources, &out.IncludeResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeResources != nil {
		in, out := &in.ExcludeResources, &out.ExcludeResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ANDedLabelSelectors != nil {
		in, out := &in.ANDedLabelSelectors, &out.ANDedLabelSelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestOptions.
func (in *ManifestOptions) DeepCopy() *ManifestOptions {
	if in == nil {
		return nil
	}
	out := new(ManifestOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PITR) DeepCopyInto(out *PITR) {
	*out = *in
	in.TargetTime.DeepCopyInto(&out.TargetTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PITR.
func (in *PITR) DeepCopy() *PITR {
	if in == nil {
		return nil
	}
	out := new(PITR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PITROverview) DeepCopyInto(out *PITROverview) {
	*out = *in
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(TimeRange)
		(*in).DeepCopyInto(*out)
	}
	if in.LastPushTime != nil {
		in, out := &in.LastPushTime, &out.LastPushTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailure != nil {
		in, out := &in.LastFailure, &out.LastFailure
		*out = new(LogFailure)
		(*in).DeepCopyInto(*out)
	}
	if in.LastRetention != nil {
		in, out := &in.LastRetention, &out.LastRetention
		*out = new(storagev1alpha1.LogRetentionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PITROverview.
func (in *PITROverview) DeepCopy() *PITROverview {
	if in == nil {
		return nil
	}
	out := new(PITROverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPOStats) DeepCopyInto(out *RPOStats) {
	*out = *in
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.WorstCase != nil {
		in, out := &in.WorstCase, &out.WorstCase
		*out = new(metav1.Duration)
		**out = **in
	}
	out.Window = in.Window
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPOStats.
func (in *RPOStats) DeepCopy() *RPOStats {
	if in == nil {
		return nil
	}
	out := new(RPOStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RTOStats) DeepCopyInto(out *RTOStats) {
	*out = *in
	if in.LastMeasured != nil {
		in, out := &in.LastMeasured, &out.LastMeasured
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LastMeasuredAt != nil {
		in, out := &in.LastMeasuredAt, &out.LastMeasuredAt
		*out = (*in).DeepCopy()
	}
	if in.Estimated != nil {
		in, out := &in.Estimated, &out.Estimated
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RTOStats.
func (in *RTOStats) DeepCopy() *RTOStats {
	if in == nil {
		return nil
	}
	out := new(RTOStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryPoint) DeepCopyInto(out *RecoveryPoint) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryPoint.
func (in *RecoveryPoint) DeepCopy() *RecoveryPoint {
	if in == nil {
		return nil
	}
	out := new(RecoveryPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryOverview) DeepCopyInto(out *RepositoryOverview) {
	*out = *in
	if in.Integrity != nil {
		in, out := &in.Integrity, &out.Integrity
		*out = new(bool)
		**out = **in
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(VerificationOverview)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryOverview.
func (in *RepositoryOverview) DeepCopy() *RepositoryOverview {
	if in == nil {
		return nil
	}
	out := new(RepositoryOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRequest) DeepCopyInto(out *RestoreRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRequest.
func (in *RestoreRequest) DeepCopy() *RestoreRequest {
	if in == nil {
		return nil
	}
	out := new(RestoreRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestoreRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRequestSpec) DeepCopyInto(out *RestoreRequestSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Clone != nil {
		in, out := &in.Clone, &out.Clone
		*out = new(CloneOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Manifest != nil {
		in, out := &in.Manifest, &out.Manifest
		*out = new(ManifestOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRequestSpec.
func (in *RestoreRequestSpec) DeepCopy() *RestoreRequestSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRequestStatus) DeepCopyInto(out *RestoreRequestStatus) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]v1.TypedObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Rendered != nil {
		in, out := &in.Rendered, &out.Rendered
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRequestStatus.
func (in *RestoreRequestStatus) DeepCopy() *RestoreRequestStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSource) DeepCopyInto(out *RestoreSource) {
	*out = *in
	if in.PITR != nil {
		in, out := &in.PITR, &out.PITR
		*out = new(PITR)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSource.
func (in *RestoreSource) DeepCopy() *RestoreSource {
	if in == nil {
		return nil
	}
	out := new(RestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionSummary) DeepCopyInto(out *RetentionSummary) {
	*out = *in
	out.Ref = in.Ref
	if in.Successful != nil {
		in, out := &in.Successful, &out.Successful
		*out = new(storagev1alpha1.SuccessfulSnapshotsKeepPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.FailedLast != nil {
		in, out := &in.FailedLast, &out.FailedLast
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionSummary.
func (in *RetentionSummary) DeepCopy() *RetentionSummary {
	if in == nil {
		return nil
	}
	out := new(RetentionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionOverview) DeepCopyInto(out *SessionOverview) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NextSchedule != nil {
		in, out := &in.NextSchedule, &out.NextSchedule
		*out = (*in).DeepCopy()
	}
	if in.LastBackup != nil {
		in, out := &in.LastBackup, &out.LastBackup
		*out = new(BackupSessionRef)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSuccessfulBackup != nil {
		in, out := &in.LastSuccessfulBackup, &out.LastSuccessfulBackup
		*out = new(BackupSessionRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]RepositoryOverview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionOverview.
func (in *SessionOverview) DeepCopy() *SessionOverview {
	if in == nil {
		return nil
	}
	out := new(SessionOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeRange) DeepCopyInto(out *TimeRange) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeRange.
func (in *TimeRange) DeepCopy() *TimeRange {
	if in == nil {
		return nil
	}
	out := new(TimeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timeline) DeepCopyInto(out *Timeline) {
	*out = *in
	in.Range.DeepCopyInto(&out.Range)
	if in.ContinuousWindows != nil {
		in, out := &in.ContinuousWindows, &out.ContinuousWindows
		*out = make([]TimeRange, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Points != nil {
		in, out := &in.Points, &out.Points
		*out = make([]RecoveryPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timeline.
func (in *Timeline) DeepCopy() *Timeline {
	if in == nil {
		return nil
	}
	out := new(Timeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationOverview) DeepCopyInto(out *VerificationOverview) {
	*out = *in
	out.Verifier = in.Verifier
	if in.NextSchedule != nil {
		in, out := &in.NextSchedule, &out.NextSchedule
		*out = (*in).DeepCopy()
	}
	if in.LastSession != nil {
		in, out := &in.LastSession, &out.LastSession
		*out = new(VerificationSessionRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationOverview.
func (in *VerificationOverview) DeepCopy() *VerificationOverview {
	if in == nil {
		return nil
	}
	out := new(VerificationOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationSessionRef) DeepCopyInto(out *VerificationSessionRef) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationSessionRef.
func (in *VerificationSessionRef) DeepCopy() *VerificationSessionRef {
	if in == nil {
		return nil
	}
	out := new(VerificationSessionRef)
	in.DeepCopyInto(out)
	return out
}
